import { FormEvent, useEffect, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { AppRole, completeManagedLogin, managedAuthEnabled, readAppUser, saveDemoUser, startManagedSocialLogin } from './auth'
import { TopicKey, topicByKey, topics } from './p1-data'
import { Feature, Icon, Page, trackEvent } from './p1-ui'

export function Home() {
  return <Page><main>
    <section className="container-page grid gap-10 pb-16 pt-14 md:grid-cols-[1.08fr_.92fr] md:items-center md:pb-24 md:pt-20">
      <div><p className="eyebrow">교통사고 사건 준비 플랫폼</p><h1 className="mt-5 max-w-xl text-[2.7rem] font-extrabold leading-[1.16] tracking-[-0.07em] text-navy sm:text-6xl">어디서부터 해야 할지<br /><span className="text-teal">3분 안에</span> 찾아보세요</h1><p className="mt-6 max-w-lg text-base leading-7 text-muted sm:text-lg">상황별 안내를 먼저 보고, 더 자세한 정리가 필요하면 AI와 자료를 함께 정리할 수 있어요.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link className="button-primary gap-3" to="/consult" onClick={() => trackEvent('consult_landing')}>무료로 내 상황 확인하기 <Icon name="arrow" size={18} /></Link><Link className="button-secondary gap-2" to="/guide/insurance-dispute" onClick={() => trackEvent('guide_start', 'insurance-dispute')}><Icon name="play" size={17} /> 3분 가이드 시작</Link></div><p className="mt-5 flex items-center gap-2 text-xs text-muted"><Icon name="info" size={14} /> 가이드는 읽기 중심, 무료상담은 질문·자료 정리 중심이에요.</p></div>
      <div className="rounded-[2rem] bg-navy p-6 text-white shadow-[0_24px_60px_rgba(21,63,88,.2)] sm:p-8"><p className="text-xs font-bold tracking-[.15em] text-[#86e1d8]">처음 오셨다면</p><h2 className="mt-4 text-2xl font-extrabold">이 순서로 시작해 보세요</h2><ol className="mt-7 space-y-4">{['가장 가까운 상황 고르기', '꼭 알아야 할 3가지 읽기', '필요하면 AI 사건정리로 이어가기'].map((item, index) => <li className="flex items-center gap-4" key={item}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-white/10 font-bold text-[#86e1d8]">{index + 1}</span><span className="text-sm font-semibold">{item}</span></li>)}</ol><p className="mt-7 rounded-2xl bg-white/10 p-4 text-xs leading-6 text-white/70">과실비율이나 승소 가능성을 정답처럼 말하지 않아요. 확인된 사실, 빠진 자료, 다음 질문을 나눠 보여드려요.</p></div>
    </section>
    <section className="border-y border-line bg-white py-14"><div className="container-page"><p className="eyebrow">내 상황에서 시작</p><h2 className="mt-3 text-2xl font-extrabold tracking-[-0.05em] text-navy sm:text-3xl">분야마다 질문과 안내가 달라요</h2><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{topics.map((topic) => <Link className="focus-ring rounded-2xl border border-line p-5 transition hover:-translate-y-0.5 hover:border-teal hover:shadow-soft" key={topic.key} to={`/guide/${topic.key}`} onClick={() => trackEvent('guide_start', topic.key)}><span className="text-3xl" aria-hidden="true">{topic.emoji}</span><div className="mt-5 flex items-start justify-between gap-3"><div><h3 className="font-bold text-navy">{topic.label}</h3><p className="mt-2 text-sm leading-5 text-muted">{topic.summary}</p></div><Icon name="arrow" size={18} /></div></Link>)}</div></div></section>
    <section className="container-page py-14"><div className="grid gap-4 md:grid-cols-3"><Feature icon="document" title="가이드는 로그인 없이" text="상황별 핵심 설명과 체크리스트를 바로 확인합니다." /><Feature icon="spark" title="AI 무료상담은 더 자세히" text="더미 또는 관리형 로그인 후 글·보험사 의견·사진을 정리합니다." /><Feature icon="user" title="판단이 필요하면 변호사로" text="출처가 있는 공개 이력과 수행사건을 비교합니다." /></div></section>
  </main></Page>
}

export function Guide() {
  const { topic: param } = useParams()
  const topic = topicByKey[param as TopicKey] || topicByKey['insurance-dispute']
  const [step, setStep] = useState(0)
  const done = step === 3
  const current = topic.guide[Math.min(step, 2)]
  return <Page><main className="pb-12"><section className="border-b border-line bg-white"><div className="container-page py-8"><Link className="focus-ring inline-flex items-center gap-2 text-sm font-semibold text-muted" to="/"><Icon name="arrowLeft" size={17} /> 상황 다시 고르기</Link><div className="mt-7 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">로그인 없는 3분 가이드</p><h1 className="mt-3 text-3xl font-extrabold tracking-[-0.06em] text-navy">{topic.emoji} {topic.label}</h1><p className="mt-3 text-sm text-muted">설명 3개를 읽은 뒤 바로 쓸 수 있는 체크리스트를 드려요.</p></div><span className="self-start rounded-full bg-[#e8f6f4] px-4 py-2 text-xs font-bold text-teal">AI 답변 아님 · 저장 안 함</span></div><div className="mt-8 flex gap-2">{topic.guide.map((_, index) => <span className={`h-1.5 flex-1 rounded-full ${index <= step ? 'bg-teal' : 'bg-line'}`} key={index} />)}</div></div></section><div className="container-page max-w-3xl py-10">{!done ? <article className="card p-6 sm:p-10"><p className="text-sm font-bold text-teal">핵심 {step + 1} / 3</p><h2 className="mt-3 text-2xl font-extrabold text-navy">{current.title}</h2><p className="mt-3 text-base leading-7 text-muted">{current.description}</p><ul className="mt-7 space-y-3">{current.points.map((point) => <li className="flex gap-3 rounded-xl bg-paper p-4 text-sm leading-6 text-navy" key={point}><span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-teal text-white"><Icon name="check" size={14} /></span>{point}</li>)}</ul><div className="mt-8 flex justify-between border-t border-line pt-6">{step > 0 ? <button className="button-secondary" onClick={() => setStep(step - 1)}>이전</button> : <span />}<button className="button-primary gap-2" onClick={() => { setStep(step + 1); if (step === 2) trackEvent('guide_complete', topic.key) }}>{step === 2 ? '체크리스트 받기' : '다음 핵심'} <Icon name="arrow" size={16} /></button></div></article> : <section className="card p-6 sm:p-10"><p className="eyebrow">3분 가이드 완료</p><h2 className="mt-3 text-2xl font-extrabold text-navy">지금 확인할 체크리스트</h2><div className="mt-6 space-y-3">{topic.checklist.map((item) => <div className="flex items-center gap-3 rounded-xl border border-line p-4 text-sm font-semibold text-navy" key={item}><Icon name="check" size={16} />{item}</div>)}</div><p className="mt-7 rounded-xl bg-cream p-5 text-sm leading-6 text-muted"><strong className="text-navy">여기까지는 일반 가이드예요.</strong><br />내 설명과 자료를 함께 정리하려면 AI 사건정리로 이어가세요.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link className="button-primary flex-1 gap-2" to={`/consult/free?topic=${topic.key}`}>무료 AI 사건정리 <Icon name="spark" size={16} /></Link><Link className="button-secondary flex-1" to="/consult/quick">간단 확인만 하기</Link></div></section>}</div></main></Page>
}

export function ConsultHub() {
  const user = readAppUser()
  return <Page><main className="container-page py-12 sm:py-16"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow">두 가지 무료 확인 방식</p><h1 className="mt-4 text-3xl font-extrabold tracking-[-0.06em] text-navy sm:text-5xl">필요한 만큼만 알려주세요</h1><p className="mt-5 text-base leading-7 text-muted">빠른 일반 안내는 간단 확인, 내 글과 자료를 정리하려면 AI 사건정리를 선택하세요.</p></div><div className="mx-auto mt-10 grid max-w-4xl gap-5 md:grid-cols-2"><ConsultCard title="간단 확인" label="약 1분 · 로그인 없음" text="상황과 진행 단계를 선택하면 규칙 기반 체크리스트를 바로 보여드려요." bullets={['분야별로 다른 선택지', '자유글·파일·AI 없음', '입력 저장 없음']} to="/consult/quick" primary={false} /><ConsultCard title="무료 AI 사건정리" label="약 3~5분 · 로그인" text="사건 설명, 보험사 의견, 사진·영상·문서 목록을 받아 Codex가 구조화합니다." bullets={['답변 주체가 AI임을 먼저 고지', '글·사진 실제 입력', '결과 뒤 변호사 또는 내 사건으로 이동']} to={user ? '/consult/free' : '/login?next=%2Fconsult%2Ffree'} primary /></div><p className="mx-auto mt-6 max-w-4xl rounded-2xl border border-[#f2dcb7] bg-cream p-5 text-sm leading-6 text-muted"><strong className="text-navy">중요:</strong> AI는 변호사가 아니며 과실비율·승소 가능성·합의금 등을 확정하지 않습니다.</p></main></Page>
}

function ConsultCard({ title, label, text, bullets, to, primary }: { title: string; label: string; text: string; bullets: string[]; to: string; primary: boolean }) {
  return <article className={`card flex flex-col p-7 ${primary ? 'border-teal' : ''}`}><span className={`flex h-12 w-12 items-center justify-center rounded-2xl ${primary ? 'bg-navy text-white' : 'bg-paper text-navy'}`}><Icon name={primary ? 'spark' : 'clock'} /></span><p className="mt-5 text-xs font-bold text-teal">{label}</p><h2 className="mt-2 text-2xl font-extrabold text-navy">{title}</h2><p className="mt-3 text-sm leading-6 text-muted">{text}</p><ul className="mt-5 space-y-2 text-sm text-muted">{bullets.map((item) => <li key={item}>✓ {item}</li>)}</ul><Link className={`${primary ? 'button-primary' : 'button-secondary'} mt-7 w-full`} to={to}>시작하기</Link></article>
}

export function QuickConsult() {
  const [topicKey, setTopicKey] = useState<TopicKey>('insurance-dispute')
  const [answer, setAnswer] = useState('')
  const topic = topicByKey[topicKey]
  return <Page><main className="container-page max-w-4xl py-12"><Link className="focus-ring inline-flex items-center gap-2 text-sm font-semibold text-muted" to="/consult"><Icon name="arrowLeft" size={17} /> 상담 방식 다시 선택</Link><p className="eyebrow mt-7">규칙 기반 간단 확인</p><h1 className="mt-3 text-3xl font-extrabold text-navy">AI 없이 빠르게 확인해요</h1><section className="card mt-8 p-6 sm:p-8"><fieldset><legend className="text-sm font-bold text-navy">1. 어떤 상황인가요?</legend><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{topics.map((item) => <button aria-pressed={topicKey === item.key} className={`focus-ring rounded-xl border p-4 text-left text-sm font-semibold ${topicKey === item.key ? 'border-teal bg-[#effaf8] text-navy' : 'border-line text-muted'}`} key={item.key} onClick={() => { setTopicKey(item.key); setAnswer('') }} type="button">{item.emoji} {item.label}</button>)}</div></fieldset><fieldset className="mt-8"><legend className="text-sm font-bold text-navy">2. {topic.branchQuestion}</legend><div className="mt-4 space-y-2">{topic.branchOptions.map((option) => <button aria-pressed={answer === option} className={`focus-ring flex min-h-12 w-full items-center justify-between rounded-xl border px-4 text-left text-sm font-semibold ${answer === option ? 'border-teal bg-[#effaf8] text-navy' : 'border-line text-muted'}`} key={option} onClick={() => setAnswer(option)} type="button"><span>{option}</span>{answer === option && <Icon name="check" size={16} />}</button>)}</div></fieldset>{answer && <div className="mt-8 border-t border-line pt-7"><p className="eyebrow">선택형 일반 결과</p><h2 className="mt-2 text-xl font-extrabold text-navy">“{answer}”라면 먼저 확인하세요</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{topic.checklist.map((item) => <div className="rounded-xl bg-paper p-4 text-sm font-semibold text-navy" key={item}>✓ {item}</div>)}</div><Link className="button-primary mt-6 gap-2" to={`/consult/free?topic=${topic.key}`}>글과 자료도 AI로 정리 <Icon name="arrow" size={16} /></Link></div>}</section></main></Page>
}

const socialProviders = [
  { key: 'kakao', label: '카카오', mark: '💬', color: '#FEE500', text: '#191919' },
  { key: 'naver', label: '네이버', mark: 'N', color: '#03C75A', text: '#ffffff' },
  { key: 'google', label: 'Google', mark: 'G', color: '#EAF1FF', text: '#3568C8' },
] as const

export function Login() {
  const [role, setRole] = useState<AppRole>('customer')
  const [error, setError] = useState('')
  const [params] = useSearchParams()
  const navigate = useNavigate()
  const requested = params.get('next') || '/app'
  const next = requested.startsWith('/') && !requested.startsWith('//') ? requested : '/app'
  const login = async (provider: typeof socialProviders[number]['key']) => {
    setError('')
    try {
      if (managedAuthEnabled && provider !== 'naver') { await startManagedSocialLogin(provider, role, next); return }
      saveDemoUser(provider, role); trackEvent('login', `${role}:${provider}:demo`); navigate(role === 'lawyer' ? '/lawyer/dashboard' : next)
    } catch (caught) { setError(caught instanceof Error ? caught.message : '로그인을 시작하지 못했습니다.') }
  }
  const emailLogin = (event: FormEvent) => { event.preventDefault(); saveDemoUser('email', role); navigate(role === 'lawyer' ? '/lawyer/dashboard' : next) }
  return <Page noFooter><main className="container-page grid min-h-[calc(100vh-72px)] gap-10 py-12 md:grid-cols-[1fr_440px] md:items-center md:gap-16"><section><p className="eyebrow">관리형 Auth + 더미 폴백</p><h1 className="mt-5 text-4xl font-extrabold leading-tight tracking-[-0.07em] text-navy sm:text-6xl">계정마다 색과 표정을<br /><span className="text-teal">한눈에 구분해요</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-muted">Supabase 키가 있으면 Google·Kakao 실제 OAuth, 없으면 더미 로그인으로 동작합니다. Naver는 별도 OAuth 연동 전까지 더미입니다.</p></section><section className="card p-6 sm:p-8"><h2 className="text-2xl font-extrabold text-navy">로그인</h2><p className="mt-2 text-sm text-muted">{managedAuthEnabled ? '관리형 Auth가 설정됐어요.' : '현재는 더미 로그인 모드예요.'}</p><div className="mt-6 grid grid-cols-2 gap-1 rounded-xl bg-paper p-1" role="tablist"><button aria-selected={role === 'customer'} className={`rounded-lg py-3 text-sm font-bold ${role === 'customer' ? 'bg-white text-navy shadow-sm' : 'text-muted'}`} onClick={() => setRole('customer')} role="tab">의뢰자</button><button aria-selected={role === 'lawyer'} className={`rounded-lg py-3 text-sm font-bold ${role === 'lawyer' ? 'bg-white text-navy shadow-sm' : 'text-muted'}`} onClick={() => setRole('lawyer')} role="tab">변호사</button></div><div className="mt-5 space-y-3">{socialProviders.map((provider) => <button className="focus-ring flex min-h-12 w-full items-center justify-center gap-3 rounded-xl border border-line font-bold" key={provider.key} onClick={() => login(provider.key)} style={{ backgroundColor: provider.color, color: provider.text }} type="button"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-white/80 font-extrabold">{provider.mark}</span>{provider.label}로 계속{provider.key === 'naver' && managedAuthEnabled ? ' (더미)' : ''}</button>)}</div><div className="my-6 flex items-center gap-3 text-xs text-muted"><span className="h-px flex-1 bg-line" />또는 더미 이메일<span className="h-px flex-1 bg-line" /></div><form className="space-y-4" onSubmit={emailLogin}><input aria-label="이메일" className="h-12 w-full rounded-xl border border-line px-4 text-sm" defaultValue="demo@ukool.local" type="email" /><input aria-label="비밀번호" className="h-12 w-full rounded-xl border border-line px-4 text-sm" defaultValue="demo1234" type="password" /><button className="button-secondary w-full" type="submit">이메일 더미 계정</button></form>{error && <p className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700" role="alert">{error}</p>}<p className="mt-5 flex gap-2 text-xs leading-5 text-muted"><Icon name="lock" size={14} /> 내 사건과 AI 사건정리는 로그인 뒤에만 열립니다.</p></section></main></Page>
}

export function AuthCallback() {
  const navigate = useNavigate()
  const [message, setMessage] = useState('관리형 로그인 정보를 확인하는 중…')
  useEffect(() => { completeManagedLogin().then((user) => { if (!user) throw new Error('로그인 세션이 없습니다.'); const next = sessionStorage.getItem('ukool-auth-next') || '/app'; navigate(user.role === 'lawyer' ? '/lawyer/dashboard' : next, { replace: true }) }).catch((error) => setMessage(error instanceof Error ? error.message : '로그인을 완료하지 못했습니다.')) }, [navigate])
  return <Page noFooter><main className="container-page flex min-h-[70vh] items-center justify-center"><div className="card max-w-md p-8 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#effaf8] text-teal"><Icon name="lock" /></span><h1 className="mt-5 text-xl font-extrabold text-navy">로그인 처리</h1><p className="mt-3 text-sm text-muted">{message}</p></div></main></Page>
}
